site_name: Documentation
site_url: https://docs.snippets3d.com
theme:
  name: material
  features:
      - version
      - content.code.copy
  palette:
    scheme: slate
    primary: custom
    accent: blue
  logo: assets/images/snippets_logo_dark_bg.svg
  favicon: assets/images/favicon.ico
extra_css:
- stylesheets/extra.css
extra:
  version:
    provider: mike
plugins:
  - mike:
      canonical_version: latest
site_name: Snippets Documentation

nav:
  - Home: index.md
  - Getting Started:
      - Create Your First Snippet Set: getting-started/create-your-first-snippet-set.md
      - Previewing and Publishing Snippets: getting-started/previewing-and-publishing-snippets.md
      - SDK Installation: getting-started/sdk-installation.md
      - SDK First Import: getting-started/sdk-first-import.md
  - SDK:
      - Overview: SDK/overview.md
      - Installation: SDK/installation.md
      - Initial Setup in Unity: SDK/initial-setup-in-unity.md
      - Snippets Project Folders: SDK/snippets-project-folders.md
      - Import, Update, Remove Snippet Sets: SDK/import-update-remove-snippet-sets.md
      - Bringing Imported Snippets Into a Scene: SDK/bringing-imported-snippets-into-a-scene.md
      - Setting Up a Scene With Helper Tools: SDK/setting-up-a-scene-with-helper-tools.md
      - Template and Playback Modes: SDK/template-and-playback-modes.md
      - Helper Tools: SDK/helper-tools.md
      - Programmer Integration Guide: SDK/programmer-integration-guide.md
      - Recommended Validation Path: SDK/recommended-validation-path.md
      - Troubleshooting: SDK/troubleshooting.md
  - Definitions: definitions.md
