site_name: Documentation
site_url: https://docs.snippets3d.com
theme:
  name: material
  palette:
    scheme: 'slate'  # This sets the theme to a dark palette
    primary: 'blue'  # Change primary color (e.g., links, buttons)
    accent: 'blue'  # Accent color
  logo: 'assets/images/snippets-logo.png'  # Optional: If you want to add a logo
  favicon: 'assets/images/favicon.ico'  # Optional: Add a favicon
