site_name: Documentation
site_url: https://docs.snippets3d.com
theme:
  name: material
  features:
      - version
      - content.code.copy
  palette:
    scheme: 'slate'  # This sets the theme to a dark palette
    primary: 'custom'  # Change primary color (e.g., links, buttons)
    accent: 'blue'  # Accent color
  logo: 'assets/images/snippets_logo_dark_bg.svg'  # Optional: If you want to add a logo
  favicon: 'assets/images/favicon.ico'  # Optional: Add a favicon
extra_css:
- stylesheets/extra.css
extra:
  version:
    provider: mike
plugins:
  - mike:
      canonical_version: latest
site_name: Snippets SDK Documentation

nav:
  - Home: index.md
  - Getting Started:
      - Create Your First Snippet Set: getting-started/create-your-first-snippet-set.md
      - Previewing and Publishing Snippets: getting-started/previewing-and-publishing-snippets.md
      - SDK Installation: getting-started/sdk-installation.md
      - SDK First Import: getting-started/sdk-first-import.md
  - SDK:
      - Create a Snippet Template: SDK/create-a-snippet-template.md
      - Customizing Folders: SDK/customizing-folders.md
  - Definitions: definitions.md

